require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.1'
prepare_react_native_project!

# RN 0.74 wants frameworks; static linkage is recommended
use_frameworks! :linkage => :static

target 'upCrib' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'upCribTests' do
    inherit! :complete
  end
end

post_install do |installer|
  # RN post install hooks
  react_native_post_install(installer)

  # Ensure all Pods produce dSYMs in Release (helps TestFlight symbol matching)
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      if config.name == 'Release'
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
      end
    end
  end
end
